# Form implementation generated from reading ui file 'resources/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(781, 376)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(450, 315))
        MainWindow.setMaximumSize(QtCore.QSize(1520, 1220))
        MainWindow.setBaseSize(QtCore.QSize(760, 610))
        MainWindow.setStyleSheet("/*\n"
" * MacOS Style Sheet for QT Applications\n"
" * Author: Jaime A. Quiroga P.\n"
" * Company: GTRONICK\n"
" * Last updated: 25/12/2020, 23:10.\n"
" * Available at: https://github.com/GTRONICK/QSS/blob/master/MacOS.qss\n"
" */\n"
"QMainWindow {\n"
"    background-color:#ececec;\n"
"}\n"
"QWidget {\n"
"    background-color:#ececec;\n"
"    border: none;\n"
"}\n"
"QPushButton, QToolButton, QCommandLinkButton{\n"
"    padding: 0 5px 0 5px;\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-right-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-width: 2px;\n"
"    border-radius: 8px;\n"
"    color: #616161;\n"
"    font-weight: bold;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #fbfdfd, stop:0.5 #ffffff, stop:1 #fbfdfd);\n"
"}\n"
"QPushButton::default, QToolButton::default, QCommandLinkButton::default{\n"
"    border: 2px solid transparent;\n"
"    color: #FFFFFF;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #84afe5, stop:1 #1168e4);\n"
"}\n"
"QPushButton:hover, QToolButton:hover, QCommandLinkButton:hover{\n"
"    color: #3d3d3d;\n"
"}\n"
"QPushButton:pressed, QToolButton:pressed, QCommandLinkButton:pressed{\n"
"    color: #aeaeae;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #ffffff, stop:0.5 #fbfdfd, stop:1 #ffffff);\n"
"}\n"
"QPushButton:disabled, QToolButton:disabled, QCommandLinkButton:disabled{\n"
"    color: #616161;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #dce7eb, stop:0.5 #e0e8eb, stop:1 #dee7ec);\n"
"}\n"
"QLineEdit, QTextEdit, QPlainTextEdit, QSpinBox, QDoubleSpinBox, QTimeEdit, QDateEdit, QDateTimeEdit {\n"
"    border-width: 2px;\n"
"    border-radius: 8px;\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    background-color: #f4f4f4;\n"
"    color: #3d3d3d;\n"
"}\n"
"QLineEdit:focus, QTextEdit:focus, QPlainTextEdit:focus, QSpinBox:focus, QDoubleSpinBox:focus, QTimeEdit:focus, QDateEdit:focus, QDateTimeEdit:focus {\n"
"    border-width: 2px;\n"
"    border-radius: 8px;\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"    border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"    background-color: #f4f4f4;\n"
"    color: #3d3d3d;\n"
"}\n"
"QLineEdit:disabled, QTextEdit:disabled, QPlainTextEdit:disabled, QSpinBox:disabled, QDoubleSpinBox:disabled, QTimeEdit:disabled, QDateEdit:disabled, QDateTimeEdit:disabled {\n"
"    color: #b9b9b9;\n"
"}\n"
"QSpinBox::up-button, QDoubleSpinBox::up-button, QTimeEdit::up-button, QDateEdit::up-button, QDateTimeEdit::up-button {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    color: #272727;\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    padding: 3px;\n"
"}\n"
"QSpinBox::down-button, QDoubleSpinBox::down-button, QTimeEdit::down-button, QDateEdit::down-button, QDateTimeEdit::down-button {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: bottom right;\n"
"    width: 15px;\n"
"    color: #272727;\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-bottom-right-radius: 3px;\n"
"    padding: 3px;\n"
"}\n"
"QSpinBox::up-button:pressed, QDoubleSpinBox::up-button:pressed, QTimeEdit::up-button:pressed, QDateEdit::up-button:pressed, QDateTimeEdit::up-button:pressed {\n"
"    color: #aeaeae;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #ffffff, stop:0.5 #fbfdfd, stop:1 #ffffff);\n"
"}\n"
"QSpinBox::down-button:pressed, QDoubleSpinBox::down-button:pressed, QTimeEdit::down-button:pressed, QDateEdit::down-button:pressed, QDateTimeEdit::down-button:pressed {\n"
"    color: #aeaeae;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #ffffff, stop:0.5 #fbfdfd, stop:1 #ffffff);\n"
"}\n"
"QSpinBox::up-button:hover, QDoubleSpinBox::up-button:hover, QTimeEdit::up-button:hover, QDateEdit::up-button:hover, QDateTimeEdit::up-button:hover {\n"
"    color: #FFFFFF;\n"
"    border-top-right-radius: 5px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #84afe5, stop:1 #1168e4);\n"
"    \n"
"}\n"
"QSpinBox::down-button:hover, QDoubleSpinBox::down-button:hover, QTimeEdit::down-button:hover, QDateEdit::down-button:hover, QDateTimeEdit::down-button:hover {\n"
"    color: #FFFFFF;\n"
"    border-bottom-right-radius: 5px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #84afe5, stop:1 #1168e4);\n"
"}\n"
"QSpinBox::up-arrow, QDoubleSpinBox::up-arrow, QTimeEdit::up-arrow, QDateEdit::up-arrow, QDateTimeEdit::up-arrow {\n"
"    image: url(/usr/share/icons/Adwaita/16x16/actions/go-up-symbolic.symbolic.png);\n"
"}\n"
"QSpinBox::down-arrow, QDoubleSpinBox::down-arrow, QTimeEdit::down-arrow, QDateEdit::down-arrow, QDateTimeEdit::down-arrow {\n"
"    image: url(/usr/share/icons/Adwaita/16x16/actions/go-down-symbolic.symbolic.png);\n"
"}\n"
"QProgressBar {\n"
"    max-height: 8px;\n"
"    text-align: center;\n"
"    font: italic bold 11px;\n"
"    color: #3d3d3d;\n"
"    border: 1px solid transparent;\n"
"    border-radius:4px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #ddd5d5, stop:0.5 #dad3d3, stop:1 #ddd5d5);\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #467dd1, stop:0.5 #3b88fc, stop:1 #467dd1);\n"
"    border-radius: 4px;\n"
"}\n"
"QProgressBar:disabled {\n"
"    color: #616161;\n"
"}\n"
"QProgressBar::chunk:disabled {\n"
"    background-color: #aeaeae;\n"
"}\n"
"QSlider::groove {\n"
"    border: 1px solid #bbbbbb;\n"
"    background-color: #52595d;\n"
"    border-radius: 4px;\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    height: 6px;\n"
"}\n"
"QSlider::groove:vertical {\n"
"    width: 6px;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    width: 12px;\n"
"    margin: -5px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    height: 12px;\n"
"    margin: 0 -5px;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::add-page, QSlider::sub-page {\n"
"    border: 1px transparent;\n"
"    background-color: #52595d;\n"
"    border-radius: 4px;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #ddd5d5, stop:0.5 #dad3d3, stop:1 #ddd5d5);\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #467dd1, stop:0.5 #3b88fc, stop:1 #467dd1);\n"
"}\n"
"QSlider::add-page:vertical {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #467dd1, stop:0.5 #3b88fc, stop:1 #467dd1);\n"
"}\n"
"QSlider::sub-page:vertical {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ddd5d5, stop:0.5 #dad3d3, stop:1 #ddd5d5);\n"
"}\n"
"QSlider::add-page:horizontal:disabled, QSlider::sub-page:horizontal:disabled, QSlider::add-page:vertical:disabled, QSlider::sub-page:vertical:disabled {\n"
"    background: #b9b9b9;\n"
"}\n"
"QComboBox, QFontComboBox {\n"
"    border-width: 2px;\n"
"    border-radius: 8px;\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    background-color: #f4f4f4;\n"
"    color: #272727;\n"
"    padding-left: 5px;\n"
"}\n"
"QComboBox:editable, QComboBox:!editable, QComboBox::drop-down:editable, QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: #ffffff;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    color: #272727;\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(/usr/share/icons/Adwaita/16x16/actions/go-down-symbolic.symbolic.png); /*Adawaita icon thene*/\n"
"}\n"
"\n"
"QComboBox::down-arrow:on {\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid darkgray;\n"
"    border-radius: 8px;\n"
"    selection-background-color: #dadada;\n"
"    selection-color: #272727;\n"
"    color: #272727;\n"
"    background: white;\n"
"}\n"
"QLabel, QCheckBox, QRadioButton {\n"
"    color: #272727;\n"
"}\n"
"QCheckBox {\n"
"    padding: 2px;\n"
"}\n"
"QCheckBox:disabled, QRadioButton:disabled {\n"
"    color: #808086;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QCheckBox:hover {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    padding-left: 1px;\n"
"    padding-right: 1px;\n"
"    padding-bottom: 1px;\n"
"    padding-top: 1px;\n"
"    border-width:1px;\n"
"    border-color: transparent;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    height: 15px;\n"
"    width: 15px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: #48a5fd;\n"
"    color: #ffffff;\n"
"    border-radius: 3px;\n"
"    background-color: rgb(223, 50, 39)\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    \n"
"    height: 15px;\n"
"    width: 15px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: #48a5fd;\n"
"    border-radius: 3px;\n"
"    background-color: #fbfdfa;\n"
"}\n"
"QLCDNumber {\n"
"    color: #616161;;\n"
"}\n"
"QMenuBar {\n"
"    background-color: #ececec;\n"
"}\n"
"QMenuBar::item {\n"
"    color: #616161;\n"
"    spacing: 3px;\n"
"    padding: 1px 4px;\n"
"    background-color: #ececec;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #dadada;\n"
"    color: #3d3d3d;\n"
"}\n"
"QMenu {\n"
"    background-color: #ececec;\n"
"}\n"
"QMenu::item:selected {\n"
"    background-color: #dadada;\n"
"    color: #3d3d3d;\n"
"}\n"
"QMenu::item {\n"
"    color: #616161;;\n"
"    background-color: #e0e0e0;\n"
"}\n"
"QTabWidget {\n"
"    color:rgb(0,0,0);\n"
"    background-color:#000000;\n"
"}\n"
"QTabWidget::pane {\n"
"    border-color: #050a0e;\n"
"    background-color: #e0e0e0;\n"
"    border-width: 1px;\n"
"    border-radius: 4px;\n"
"    position: absolute;\n"
"    top: -0.5em;\n"
"    padding-top: 0.5em;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    alignment: center;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    border-bottom: 1px solid #c0c0c0;\n"
"    padding: 3px;\n"
"    color: #272727;\n"
"    background-color: #fefefc;\n"
"    margin-left:0px;\n"
"}\n"
"QTabBar::tab:!last {\n"
"    border-right: 1px solid;\n"
"    border-right-color: #c0c0c0;\n"
"    border-bottom-color: #c0c0c0;\n"
"}\n"
"QTabBar::tab:first {\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"}\n"
"QTabBar::tab:last {\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:hover {\n"
"    color: #FFFFFF;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #84afe5, stop:1 #1168e4);\n"
"}\n"
"QRadioButton::indicator {\n"
"    height: 14px;\n"
"    width: 14px;\n"
"    border-style:solid;\n"
"    border-radius:7px;\n"
"    border-width: 1px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    border-color: #48a5fd;\n"
"    background-color: qradialgradient(cx:0.5, cy:0.5, radius:0.4,fx:0.5, fy:0.5, stop:0 #ffffff, stop:0.5 #ffffff, stop:0.6 #48a5fd, stop:1 #48a5fd);\n"
"}\n"
"QRadioButton::indicator:!checked {\n"
"    border-color: #a9b7c6;\n"
"    background-color: #fbfdfa;\n"
"}\n"
"QStatusBar {\n"
"    color:#027f7f;\n"
"}\n"
"\n"
"QDial {\n"
"    background: #16a085;\n"
"}\n"
"\n"
"QToolBox {\n"
"    color: #a9b7c6;\n"
"    background-color: #222b2e;\n"
"}\n"
"QToolBox::tab {\n"
"    color: #a9b7c6;\n"
"    background-color:#222b2e;\n"
"}\n"
"QToolBox::tab:selected {\n"
"    color: #FFFFFF;\n"
"    background-color:#222b2e;\n"
"}\n"
"QScrollArea {\n"
"    color: #FFFFFF;\n"
"    background-color:#222b2e;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    max-height: 10px;\n"
"    border: 1px transparent grey;\n"
"    margin: 0px 20px 0px 20px;\n"
"    background: transparent;\n"
"}\n"
"QScrollBar:vertical {\n"
"    max-width: 10px;\n"
"    border: 1px transparent grey;\n"
"    margin: 20px 0px 20px 0px;\n"
"    background: transparent;\n"
"}\n"
"QScrollBar::handle:vertical, QScrollBar::handle:horizontal {\n"
"    background: #52595d;\n"
"    border-style: transparent;\n"
"    border-radius: 4px;\n"
"    min-height: 25px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover, QScrollBar::handle:vertical:hover {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #467dd1, stop:0.5 #3b88fc, stop:1 #467dd1);\n"
"}\n"
"QScrollBar::add-line, QScrollBar::sub-line {\n"
"    border: 2px transparent grey;\n"
"    border-radius: 4px;\n"
"    subcontrol-origin: margin;\n"
"    background: #b9b9b9;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    width: 20px;\n"
"    subcontrol-position: right;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    height: 20px;\n"
"    subcontrol-position: bottom;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    width: 20px;\n"
"    subcontrol-position: left;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 20px;\n"
"    subcontrol-position: top;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed, QScrollBar::add-line:horizontal:pressed, QScrollBar::sub-line:horizontal:pressed, QScrollBar::sub-line:vertical:pressed {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #467dd1, stop:0.5 #3b88fc, stop:1 #467dd1);\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal, QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::up-arrow:vertical {\n"
"    image: url(/usr/share/icons/Adwaita/16x16/actions/go-up-symbolic.symbolic.png);\n"
"}\n"
"QScrollBar::down-arrow:vertical {\n"
"    image: url(/usr/share/icons/Adwaita/16x16/actions/go-down-symbolic.symbolic.png);\n"
"}\n"
"QScrollBar::left-arrow:horizontal {\n"
"    image: url(/usr/share/icons/Adwaita/16x16/actions/go-previous-symbolic.symbolic.png);\n"
"}\n"
"QScrollBar::right-arrow:horizontal {\n"
"    image: url(/usr/share/icons/Adwaita/16x16/actions/go-next-symbolic.symbolic.png);\n"
"}")
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(380, 305))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sidePanel = QtWidgets.QWidget(parent=self.centralwidget)
        self.sidePanel.setEnabled(True)
        self.sidePanel.setMinimumSize(QtCore.QSize(130, 300))
        self.sidePanel.setBaseSize(QtCore.QSize(130, 0))
        self.sidePanel.setStyleSheet("QWidget {\n"
"    background-color: rgb(206, 180, 158);\n"
"}\n"
"\n"
"QPushButton {\n"
"    text-align: center;\n"
"    height: 30px;\n"
"    border: none;\n"
"}\n"
"QPushButton:checked {\n"
" color: rgb(0, 82, 155);\n"
"font-weight: bold;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(177, 65, 56);\n"
"}")
        self.sidePanel.setObjectName("sidePanel")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sidePanel)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(10, 20, 10, 40)
        self.verticalLayout_2.setSpacing(40)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.logoLabel = QtWidgets.QLabel(parent=self.sidePanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logoLabel.sizePolicy().hasHeightForWidth())
        self.logoLabel.setSizePolicy(sizePolicy)
        self.logoLabel.setMaximumSize(QtCore.QSize(130, 90))
        self.logoLabel.setText("")
        self.logoLabel.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.logoLabel.setPixmap(QtGui.QPixmap("resources/images/US_Air_Force_Logo_Solid_Colour.svg"))
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logoLabel.setObjectName("logoLabel")
        self.verticalLayout_2.addWidget(self.logoLabel)
        self.verticalButtonLayout = QtWidgets.QVBoxLayout()
        self.verticalButtonLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.verticalButtonLayout.setSpacing(20)
        self.verticalButtonLayout.setObjectName("verticalButtonLayout")
        self.pushButton = QtWidgets.QPushButton(parent=self.sidePanel)
        self.pushButton.setCheckable(True)
        self.pushButton.setChecked(True)
        self.pushButton.setAutoExclusive(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalButtonLayout.addWidget(self.pushButton)
        self.metaButton = QtWidgets.QPushButton(parent=self.sidePanel)
        self.metaButton.setCheckable(True)
        self.metaButton.setChecked(False)
        self.metaButton.setAutoExclusive(True)
        self.metaButton.setObjectName("metaButton")
        self.verticalButtonLayout.addWidget(self.metaButton)
        self.aiButton = QtWidgets.QPushButton(parent=self.sidePanel)
        self.aiButton.setEnabled(True)
        self.aiButton.setCheckable(True)
        self.aiButton.setAutoExclusive(True)
        self.aiButton.setObjectName("aiButton")
        self.verticalButtonLayout.addWidget(self.aiButton)
        self.verticalLayout_2.addLayout(self.verticalButtonLayout)
        self.quitButton = QtWidgets.QPushButton(parent=self.sidePanel)
        self.quitButton.setCheckable(True)
        self.quitButton.setObjectName("quitButton")
        self.verticalLayout_2.addWidget(self.quitButton)
        self.horizontalLayout.addWidget(self.sidePanel)
        self.mainMenu = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainMenu.sizePolicy().hasHeightForWidth())
        self.mainMenu.setSizePolicy(sizePolicy)
        self.mainMenu.setStyleSheet("")
        self.mainMenu.setObjectName("mainMenu")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainMenu)
        self.verticalLayout.setContentsMargins(2, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerFirstColumnLayoutV = QtWidgets.QVBoxLayout()
        self.headerFirstColumnLayoutV.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.headerFirstColumnLayoutV.setContentsMargins(-1, 20, -1, 10)
        self.headerFirstColumnLayoutV.setSpacing(10)
        self.headerFirstColumnLayoutV.setObjectName("headerFirstColumnLayoutV")
        self.virinExiftoolLabel = QtWidgets.QLabel(parent=self.mainMenu)
        self.virinExiftoolLabel.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        self.virinExiftoolLabel.setFont(font)
        self.virinExiftoolLabel.setStyleSheet("")
        self.virinExiftoolLabel.setScaledContents(True)
        self.virinExiftoolLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.virinExiftoolLabel.setObjectName("virinExiftoolLabel")
        self.headerFirstColumnLayoutV.addWidget(self.virinExiftoolLabel)
        self.fileOpenLayout = QtWidgets.QHBoxLayout()
        self.fileOpenLayout.setContentsMargins(35, -1, 33, -1)
        self.fileOpenLayout.setObjectName("fileOpenLayout")
        self.openButton = QtWidgets.QPushButton(parent=self.mainMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openButton.sizePolicy().hasHeightForWidth())
        self.openButton.setSizePolicy(sizePolicy)
        self.openButton.setObjectName("openButton")
        self.fileOpenLayout.addWidget(self.openButton)
        self.pathLabel = QtWidgets.QLabel(parent=self.mainMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathLabel.sizePolicy().hasHeightForWidth())
        self.pathLabel.setSizePolicy(sizePolicy)
        self.pathLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.pathLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pathLabel.setStyleSheet("QLabel {\n"
"    border-width: 2px;\n"
"    border-radius: 8px;\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    background-color: #f4f4f4;\n"
"    color: #3d3d3d;\n"
"}")
        self.pathLabel.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.pathLabel.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.pathLabel.setText("")
        self.pathLabel.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.pathLabel.setScaledContents(False)
        self.pathLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.pathLabel.setWordWrap(False)
        self.pathLabel.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextEditable|QtCore.Qt.TextInteractionFlag.TextEditorInteraction|QtCore.Qt.TextInteractionFlag.TextSelectableByKeyboard|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.pathLabel.setObjectName("pathLabel")
        self.fileOpenLayout.addWidget(self.pathLabel)
        self.headerFirstColumnLayoutV.addLayout(self.fileOpenLayout)
        self.verticalLayout.addLayout(self.headerFirstColumnLayoutV)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.mainMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMaximumSize(QtCore.QSize(650, 750))
        self.stackedWidget.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.stackedWidget.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.stackedWidget.setStatusTip("")
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.stackedWidget.setObjectName("stackedWidget")
        self.filePage = QtWidgets.QWidget()
        self.filePage.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filePage.sizePolicy().hasHeightForWidth())
        self.filePage.setSizePolicy(sizePolicy)
        self.filePage.setMinimumSize(QtCore.QSize(646, 0))
        self.filePage.setMaximumSize(QtCore.QSize(646, 16777215))
        self.filePage.setStyleSheet("")
        self.filePage.setObjectName("filePage")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.filePage)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.mainFilenameLayoutH = QtWidgets.QHBoxLayout()
        self.mainFilenameLayoutH.setSpacing(6)
        self.mainFilenameLayoutH.setObjectName("mainFilenameLayoutH")
        self.filenameFirstColumnLayoutV = QtWidgets.QVBoxLayout()
        self.filenameFirstColumnLayoutV.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.filenameFirstColumnLayoutV.setContentsMargins(-1, -1, 0, -1)
        self.filenameFirstColumnLayoutV.setSpacing(0)
        self.filenameFirstColumnLayoutV.setObjectName("filenameFirstColumnLayoutV")
        self.filenameHorizontalLayout = QtWidgets.QHBoxLayout()
        self.filenameHorizontalLayout.setContentsMargins(50, 75, 100, -1)
        self.filenameHorizontalLayout.setSpacing(0)
        self.filenameHorizontalLayout.setObjectName("filenameHorizontalLayout")
        self.dateOverrideCheckBox = QtWidgets.QCheckBox(parent=self.filePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateOverrideCheckBox.sizePolicy().hasHeightForWidth())
        self.dateOverrideCheckBox.setSizePolicy(sizePolicy)
        self.dateOverrideCheckBox.setMinimumSize(QtCore.QSize(150, 0))
        self.dateOverrideCheckBox.setAcceptDrops(False)
        self.dateOverrideCheckBox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.dateOverrideCheckBox.setAutoFillBackground(False)
        self.dateOverrideCheckBox.setChecked(False)
        self.dateOverrideCheckBox.setObjectName("dateOverrideCheckBox")
        self.filenameHorizontalLayout.addWidget(self.dateOverrideCheckBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.filenameHorizontalLayout.addItem(spacerItem)
        self.dateEdit = QtWidgets.QLineEdit(parent=self.filePage)
        self.dateEdit.setEnabled(False)
        self.dateEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.dateEdit.setMaximumSize(QtCore.QSize(90, 16777215))
        self.dateEdit.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.dateEdit.setAutoFillBackground(False)
        self.dateEdit.setInputMask("")
        self.dateEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dateEdit.setClearButtonEnabled(False)
        self.dateEdit.setObjectName("dateEdit")
        self.filenameHorizontalLayout.addWidget(self.dateEdit)
        self.virinLabel = QtWidgets.QLabel(parent=self.filePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.virinLabel.sizePolicy().hasHeightForWidth())
        self.virinLabel.setSizePolicy(sizePolicy)
        self.virinLabel.setMaximumSize(QtCore.QSize(70, 16777215))
        self.virinLabel.setObjectName("virinLabel")
        self.filenameHorizontalLayout.addWidget(self.virinLabel)
        self.shotEdit = QtWidgets.QLineEdit(parent=self.filePage)
        self.shotEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.shotEdit.setMouseTracking(True)
        self.shotEdit.setInputMask("")
        self.shotEdit.setCursorPosition(0)
        self.shotEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.shotEdit.setObjectName("shotEdit")
        self.filenameHorizontalLayout.addWidget(self.shotEdit)
        self.seqEdit = QtWidgets.QLineEdit(parent=self.filePage)
        self.seqEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.seqEdit.setMouseTracking(True)
        self.seqEdit.setInputMask("")
        self.seqEdit.setFrame(True)
        self.seqEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.seqEdit.setCursorPosition(0)
        self.seqEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.seqEdit.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.seqEdit.setClearButtonEnabled(False)
        self.seqEdit.setObjectName("seqEdit")
        self.filenameHorizontalLayout.addWidget(self.seqEdit)
        self.filenameFirstColumnLayoutV.addLayout(self.filenameHorizontalLayout)
        self.filenameHorizontalLayout3 = QtWidgets.QHBoxLayout()
        self.filenameHorizontalLayout3.setContentsMargins(-1, -1, 100, 75)
        self.filenameHorizontalLayout3.setSpacing(20)
        self.filenameHorizontalLayout3.setObjectName("filenameHorizontalLayout3")
        self.fileFormatLabel = QtWidgets.QLabel(parent=self.filePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileFormatLabel.sizePolicy().hasHeightForWidth())
        self.fileFormatLabel.setSizePolicy(sizePolicy)
        self.fileFormatLabel.setMinimumSize(QtCore.QSize(150, 0))
        self.fileFormatLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.fileFormatLabel.setObjectName("fileFormatLabel")
        self.filenameHorizontalLayout3.addWidget(self.fileFormatLabel)
        self.fileFormatComboBox = QtWidgets.QComboBox(parent=self.filePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileFormatComboBox.sizePolicy().hasHeightForWidth())
        self.fileFormatComboBox.setSizePolicy(sizePolicy)
        self.fileFormatComboBox.setMinimumSize(QtCore.QSize(75, 0))
        self.fileFormatComboBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.fileFormatComboBox.setObjectName("fileFormatComboBox")
        self.fileFormatComboBox.addItem("")
        self.fileFormatComboBox.addItem("")
        self.fileFormatComboBox.addItem("")
        self.fileFormatComboBox.addItem("")
        self.fileFormatComboBox.addItem("")
        self.fileFormatComboBox.addItem("")
        self.fileFormatComboBox.addItem("")
        self.fileFormatComboBox.addItem("")
        self.fileFormatComboBox.addItem("")
        self.fileFormatComboBox.addItem("")
        self.fileFormatComboBox.addItem("")
        self.fileFormatComboBox.addItem("")
        self.fileFormatComboBox.addItem("")
        self.fileFormatComboBox.addItem("")
        self.fileFormatComboBox.addItem("")
        self.fileFormatComboBox.addItem("")
        self.fileFormatComboBox.addItem("")
        self.fileFormatComboBox.addItem("")
        self.fileFormatComboBox.addItem("")
        self.fileFormatComboBox.addItem("")
        self.fileFormatComboBox.addItem("")
        self.fileFormatComboBox.addItem("")
        self.fileFormatComboBox.addItem("")
        self.fileFormatComboBox.addItem("")
        self.fileFormatComboBox.addItem("")
        self.fileFormatComboBox.addItem("")
        self.fileFormatComboBox.addItem("")
        self.filenameHorizontalLayout3.addWidget(self.fileFormatComboBox)
        self.resetButton = QtWidgets.QPushButton(parent=self.filePage)
        self.resetButton.setObjectName("resetButton")
        self.filenameHorizontalLayout3.addWidget(self.resetButton)
        self.undoButton = QtWidgets.QPushButton(parent=self.filePage)
        self.undoButton.setObjectName("undoButton")
        self.filenameHorizontalLayout3.addWidget(self.undoButton)
        self.renameButton = QtWidgets.QPushButton(parent=self.filePage)
        self.renameButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(219, 137, 138)\n"
"}\n"
"")
        self.renameButton.setObjectName("renameButton")
        self.filenameHorizontalLayout3.addWidget(self.renameButton)
        self.filenameFirstColumnLayoutV.addLayout(self.filenameHorizontalLayout3)
        self.mainFilenameLayoutH.addLayout(self.filenameFirstColumnLayoutV)
        self.horizontalLayout_4.addLayout(self.mainFilenameLayoutH)
        self.stackedWidget.addWidget(self.filePage)
        self.metaPage = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.metaPage.sizePolicy().hasHeightForWidth())
        self.metaPage.setSizePolicy(sizePolicy)
        self.metaPage.setStyleSheet("")
        self.metaPage.setObjectName("metaPage")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.metaPage)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.metaScrollArea = QtWidgets.QScrollArea(parent=self.metaPage)
        self.metaScrollArea.setEnabled(True)
        self.metaScrollArea.setStyleSheet("")
        self.metaScrollArea.setWidgetResizable(True)
        self.metaScrollArea.setObjectName("metaScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setEnabled(True)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 636, 435))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContents.setMouseTracking(False)
        self.scrollAreaWidgetContents.setAutoFillBackground(False)
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.fileFormatLayout = QtWidgets.QHBoxLayout()
        self.fileFormatLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.fileFormatLayout.setContentsMargins(245, 0, 20, 0)
        self.fileFormatLayout.setObjectName("fileFormatLayout")
        self.metaFileFormatLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.metaFileFormatLabel.setObjectName("metaFileFormatLabel")
        self.fileFormatLayout.addWidget(self.metaFileFormatLabel)
        self.metaFileFormatComboBox = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.metaFileFormatComboBox.setObjectName("metaFileFormatComboBox")
        self.metaFileFormatComboBox.addItem("")
        self.metaFileFormatComboBox.addItem("")
        self.metaFileFormatComboBox.addItem("")
        self.metaFileFormatComboBox.addItem("")
        self.metaFileFormatComboBox.addItem("")
        self.metaFileFormatComboBox.addItem("")
        self.metaFileFormatComboBox.addItem("")
        self.metaFileFormatComboBox.addItem("")
        self.metaFileFormatComboBox.addItem("")
        self.metaFileFormatComboBox.addItem("")
        self.metaFileFormatComboBox.addItem("")
        self.metaFileFormatComboBox.addItem("")
        self.metaFileFormatComboBox.addItem("")
        self.metaFileFormatComboBox.addItem("")
        self.metaFileFormatComboBox.addItem("")
        self.metaFileFormatComboBox.addItem("")
        self.metaFileFormatComboBox.addItem("")
        self.metaFileFormatComboBox.addItem("")
        self.metaFileFormatComboBox.addItem("")
        self.metaFileFormatComboBox.addItem("")
        self.metaFileFormatComboBox.addItem("")
        self.metaFileFormatComboBox.addItem("")
        self.metaFileFormatComboBox.addItem("")
        self.metaFileFormatComboBox.addItem("")
        self.metaFileFormatComboBox.addItem("")
        self.metaFileFormatComboBox.addItem("")
        self.metaFileFormatComboBox.addItem("")
        self.metaFileFormatComboBox.addItem("")
        self.metaFileFormatComboBox.addItem("")
        self.metaFileFormatComboBox.addItem("")
        self.metaFileFormatComboBox.addItem("")
        self.metaFileFormatComboBox.addItem("")
        self.fileFormatLayout.addWidget(self.metaFileFormatComboBox)
        self.verticalLayout_3.addLayout(self.fileFormatLayout)
        self.creatorLayout = QtWidgets.QHBoxLayout()
        self.creatorLayout.setContentsMargins(20, -1, 20, -1)
        self.creatorLayout.setSpacing(100)
        self.creatorLayout.setObjectName("creatorLayout")
        self.creatorLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.creatorLabel.setMinimumSize(QtCore.QSize(125, 0))
        self.creatorLabel.setObjectName("creatorLabel")
        self.creatorLayout.addWidget(self.creatorLabel)
        self.creatorEdit = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.creatorEdit.setObjectName("creatorEdit")
        self.creatorLayout.addWidget(self.creatorEdit)
        self.verticalLayout_3.addLayout(self.creatorLayout)
        self.titleLayout = QtWidgets.QHBoxLayout()
        self.titleLayout.setContentsMargins(20, -1, 20, -1)
        self.titleLayout.setSpacing(100)
        self.titleLayout.setObjectName("titleLayout")
        self.titleLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.titleLabel.setMinimumSize(QtCore.QSize(125, 0))
        self.titleLabel.setObjectName("titleLabel")
        self.titleLayout.addWidget(self.titleLabel)
        self.titleEdit = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.titleEdit.setObjectName("titleEdit")
        self.titleLayout.addWidget(self.titleEdit)
        self.verticalLayout_3.addLayout(self.titleLayout)
        self.descriptionLayout = QtWidgets.QHBoxLayout()
        self.descriptionLayout.setContentsMargins(20, -1, 20, -1)
        self.descriptionLayout.setSpacing(100)
        self.descriptionLayout.setObjectName("descriptionLayout")
        self.descriptionLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.descriptionLabel.setMinimumSize(QtCore.QSize(125, 0))
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.descriptionLayout.addWidget(self.descriptionLabel)
        self.descriptionEdit = QtWidgets.QPlainTextEdit(parent=self.scrollAreaWidgetContents)
        self.descriptionEdit.setStyleSheet("")
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.descriptionLayout.addWidget(self.descriptionEdit)
        self.verticalLayout_3.addLayout(self.descriptionLayout)
        self.writerLayout = QtWidgets.QHBoxLayout()
        self.writerLayout.setContentsMargins(20, -1, 20, -1)
        self.writerLayout.setSpacing(100)
        self.writerLayout.setObjectName("writerLayout")
        self.writerLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.writerLabel.setMinimumSize(QtCore.QSize(125, 0))
        self.writerLabel.setObjectName("writerLabel")
        self.writerLayout.addWidget(self.writerLabel)
        self.writerEdit = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.writerEdit.setObjectName("writerEdit")
        self.writerLayout.addWidget(self.writerEdit)
        self.verticalLayout_3.addLayout(self.writerLayout)
        self.keywordsLayout = QtWidgets.QHBoxLayout()
        self.keywordsLayout.setContentsMargins(20, -1, 20, -1)
        self.keywordsLayout.setSpacing(100)
        self.keywordsLayout.setObjectName("keywordsLayout")
        self.keywordLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.keywordLabel.setMinimumSize(QtCore.QSize(125, 0))
        self.keywordLabel.setObjectName("keywordLabel")
        self.keywordsLayout.addWidget(self.keywordLabel)
        self.keywordEdit = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.keywordEdit.setObjectName("keywordEdit")
        self.keywordsLayout.addWidget(self.keywordEdit)
        self.verticalLayout_3.addLayout(self.keywordsLayout)
        self.cityLayout = QtWidgets.QHBoxLayout()
        self.cityLayout.setContentsMargins(20, -1, 20, -1)
        self.cityLayout.setSpacing(100)
        self.cityLayout.setObjectName("cityLayout")
        self.cityLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.cityLabel.setMinimumSize(QtCore.QSize(125, 0))
        self.cityLabel.setObjectName("cityLabel")
        self.cityLayout.addWidget(self.cityLabel)
        self.cityEdit = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.cityEdit.setObjectName("cityEdit")
        self.cityLayout.addWidget(self.cityEdit)
        self.verticalLayout_3.addLayout(self.cityLayout)
        self.stateLayout = QtWidgets.QHBoxLayout()
        self.stateLayout.setContentsMargins(20, -1, 20, -1)
        self.stateLayout.setSpacing(100)
        self.stateLayout.setObjectName("stateLayout")
        self.stateLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.stateLabel.setMinimumSize(QtCore.QSize(125, 0))
        self.stateLabel.setObjectName("stateLabel")
        self.stateLayout.addWidget(self.stateLabel)
        self.stateEdit = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.stateEdit.setObjectName("stateEdit")
        self.stateLayout.addWidget(self.stateEdit)
        self.verticalLayout_3.addLayout(self.stateLayout)
        self.countyLayout = QtWidgets.QHBoxLayout()
        self.countyLayout.setContentsMargins(20, -1, 20, -1)
        self.countyLayout.setSpacing(100)
        self.countyLayout.setObjectName("countyLayout")
        self.countryLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.countryLabel.setMinimumSize(QtCore.QSize(125, 0))
        self.countryLabel.setMaximumSize(QtCore.QSize(125, 16777215))
        self.countryLabel.setObjectName("countryLabel")
        self.countyLayout.addWidget(self.countryLabel)
        self.countryEdit = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.countryEdit.setObjectName("countryEdit")
        self.countyLayout.addWidget(self.countryEdit)
        self.verticalLayout_3.addLayout(self.countyLayout)
        self.copyrightLayout = QtWidgets.QHBoxLayout()
        self.copyrightLayout.setContentsMargins(20, -1, 20, -1)
        self.copyrightLayout.setSpacing(100)
        self.copyrightLayout.setObjectName("copyrightLayout")
        self.copyrightLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.copyrightLabel.setMinimumSize(QtCore.QSize(125, 0))
        self.copyrightLabel.setMaximumSize(QtCore.QSize(125, 16777215))
        self.copyrightLabel.setObjectName("copyrightLabel")
        self.copyrightLayout.addWidget(self.copyrightLabel)
        self.copyrightEdit = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.copyrightEdit.setReadOnly(True)
        self.copyrightEdit.setObjectName("copyrightEdit")
        self.copyrightLayout.addWidget(self.copyrightEdit)
        self.verticalLayout_3.addLayout(self.copyrightLayout)
        self.metaButtonLayout = QtWidgets.QHBoxLayout()
        self.metaButtonLayout.setContentsMargins(305, -1, 80, -1)
        self.metaButtonLayout.setSpacing(0)
        self.metaButtonLayout.setObjectName("metaButtonLayout")
        self.loadButton = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.loadButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.loadButton.setObjectName("loadButton")
        self.metaButtonLayout.addWidget(self.loadButton)
        self.clearButton = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.clearButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.clearButton.setObjectName("clearButton")
        self.metaButtonLayout.addWidget(self.clearButton)
        self.writeButton = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.writeButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.writeButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(219, 137, 138)\n"
"}\n"
"")
        self.writeButton.setObjectName("writeButton")
        self.metaButtonLayout.addWidget(self.writeButton)
        self.verticalLayout_3.addLayout(self.metaButtonLayout)
        self.metaScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.metaScrollArea)
        self.stackedWidget.addWidget(self.metaPage)
        self.aiPage = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aiPage.sizePolicy().hasHeightForWidth())
        self.aiPage.setSizePolicy(sizePolicy)
        self.aiPage.setMinimumSize(QtCore.QSize(646, 0))
        self.aiPage.setMaximumSize(QtCore.QSize(646, 16777215))
        font = QtGui.QFont()
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.aiPage.setFont(font)
        self.aiPage.setStyleSheet("")
        self.aiPage.setObjectName("aiPage")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.aiPage)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.aiScrollArea = QtWidgets.QScrollArea(parent=self.aiPage)
        self.aiScrollArea.setWidgetResizable(True)
        self.aiScrollArea.setObjectName("aiScrollArea")
        self.aiScrollContents = QtWidgets.QWidget()
        self.aiScrollContents.setGeometry(QtCore.QRect(0, 0, 646, 288))
        self.aiScrollContents.setObjectName("aiScrollContents")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.aiScrollContents)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.aiVerticalLayout = QtWidgets.QVBoxLayout()
        self.aiVerticalLayout.setSpacing(10)
        self.aiVerticalLayout.setObjectName("aiVerticalLayout")
        self.aiHorizontalLayout1 = QtWidgets.QHBoxLayout()
        self.aiHorizontalLayout1.setContentsMargins(20, -1, 20, -1)
        self.aiHorizontalLayout1.setObjectName("aiHorizontalLayout1")
        self.aiInputBoxEdit = QtWidgets.QPlainTextEdit(parent=self.aiScrollContents)
        self.aiInputBoxEdit.setStyleSheet("")
        self.aiInputBoxEdit.setObjectName("aiInputBoxEdit")
        self.aiHorizontalLayout1.addWidget(self.aiInputBoxEdit)
        self.aiOutputBox = QtWidgets.QPlainTextEdit(parent=self.aiScrollContents)
        self.aiOutputBox.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextSelectableByKeyboard|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.aiOutputBox.setObjectName("aiOutputBox")
        self.aiHorizontalLayout1.addWidget(self.aiOutputBox)
        self.aiVerticalLayout.addLayout(self.aiHorizontalLayout1)
        self.aiHorizontalLayout2 = QtWidgets.QHBoxLayout()
        self.aiHorizontalLayout2.setContentsMargins(20, -1, 350, -1)
        self.aiHorizontalLayout2.setObjectName("aiHorizontalLayout2")
        self.aiResetButton = QtWidgets.QPushButton(parent=self.aiScrollContents)
        self.aiResetButton.setObjectName("aiResetButton")
        self.aiHorizontalLayout2.addWidget(self.aiResetButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.aiHorizontalLayout2.addItem(spacerItem1)
        self.aiSubmitButton = QtWidgets.QPushButton(parent=self.aiScrollContents)
        self.aiSubmitButton.setObjectName("aiSubmitButton")
        self.aiHorizontalLayout2.addWidget(self.aiSubmitButton)
        self.aiVerticalLayout.addLayout(self.aiHorizontalLayout2)
        self.horizontalLayout_3.addLayout(self.aiVerticalLayout)
        self.aiScrollArea.setWidget(self.aiScrollContents)
        self.horizontalLayout_2.addWidget(self.aiScrollArea)
        self.stackedWidget.addWidget(self.aiPage)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.mainMenu)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.quitButton.clicked.connect(MainWindow.close) # type: ignore
        self.dateOverrideCheckBox.clicked['bool'].connect(self.dateEdit.setEnabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Filename"))
        self.metaButton.setText(_translate("MainWindow", "Metadata"))
        self.aiButton.setText(_translate("MainWindow", "AI Caption"))
        self.quitButton.setText(_translate("MainWindow", "Quit"))
        self.virinExiftoolLabel.setText(_translate("MainWindow", "VIRIN XMP Toolkit"))
        self.openButton.setText(_translate("MainWindow", "Folder"))
        self.dateOverrideCheckBox.setText(_translate("MainWindow", "Date Override"))
        self.dateEdit.setPlaceholderText(_translate("MainWindow", "YYYYMMDD"))
        self.virinLabel.setText(_translate("MainWindow", "-F-F3963-"))
        self.shotEdit.setPlaceholderText(_translate("MainWindow", "Shot #"))
        self.seqEdit.setPlaceholderText(_translate("MainWindow", "Seq #"))
        self.fileFormatLabel.setText(_translate("MainWindow", "File Format:"))
        self.fileFormatComboBox.setItemText(0, _translate("MainWindow", "aiff"))
        self.fileFormatComboBox.setItemText(1, _translate("MainWindow", "avi"))
        self.fileFormatComboBox.setItemText(2, _translate("MainWindow", "cr2"))
        self.fileFormatComboBox.setItemText(3, _translate("MainWindow", "cr3"))
        self.fileFormatComboBox.setItemText(4, _translate("MainWindow", "dng"))
        self.fileFormatComboBox.setItemText(5, _translate("MainWindow", "flac"))
        self.fileFormatComboBox.setItemText(6, _translate("MainWindow", "flv"))
        self.fileFormatComboBox.setItemText(7, _translate("MainWindow", "heic"))
        self.fileFormatComboBox.setItemText(8, _translate("MainWindow", "heif"))
        self.fileFormatComboBox.setItemText(9, _translate("MainWindow", "jpeg"))
        self.fileFormatComboBox.setItemText(10, _translate("MainWindow", "jpg"))
        self.fileFormatComboBox.setItemText(11, _translate("MainWindow", "mkv"))
        self.fileFormatComboBox.setItemText(12, _translate("MainWindow", "mov"))
        self.fileFormatComboBox.setItemText(13, _translate("MainWindow", "mp3"))
        self.fileFormatComboBox.setItemText(14, _translate("MainWindow", "mp4"))
        self.fileFormatComboBox.setItemText(15, _translate("MainWindow", "mxf"))
        self.fileFormatComboBox.setItemText(16, _translate("MainWindow", "m4a"))
        self.fileFormatComboBox.setItemText(17, _translate("MainWindow", "nef"))
        self.fileFormatComboBox.setItemText(18, _translate("MainWindow", "png"))
        self.fileFormatComboBox.setItemText(19, _translate("MainWindow", "raw"))
        self.fileFormatComboBox.setItemText(20, _translate("MainWindow", "srf"))
        self.fileFormatComboBox.setItemText(21, _translate("MainWindow", "srw"))
        self.fileFormatComboBox.setItemText(22, _translate("MainWindow", "sr2"))
        self.fileFormatComboBox.setItemText(23, _translate("MainWindow", "tiff"))
        self.fileFormatComboBox.setItemText(24, _translate("MainWindow", "wav"))
        self.fileFormatComboBox.setItemText(25, _translate("MainWindow", "wma"))
        self.fileFormatComboBox.setItemText(26, _translate("MainWindow", "wmv"))
        self.resetButton.setText(_translate("MainWindow", "Reset"))
        self.undoButton.setText(_translate("MainWindow", "Undo"))
        self.renameButton.setText(_translate("MainWindow", "Rename"))
        self.metaFileFormatLabel.setText(_translate("MainWindow", "File Format:"))
        self.metaFileFormatComboBox.setItemText(0, _translate("MainWindow", "3g2"))
        self.metaFileFormatComboBox.setItemText(1, _translate("MainWindow", "3gp"))
        self.metaFileFormatComboBox.setItemText(2, _translate("MainWindow", "aax"))
        self.metaFileFormatComboBox.setItemText(3, _translate("MainWindow", "ai"))
        self.metaFileFormatComboBox.setItemText(4, _translate("MainWindow", "avif"))
        self.metaFileFormatComboBox.setItemText(5, _translate("MainWindow", "cr2"))
        self.metaFileFormatComboBox.setItemText(6, _translate("MainWindow", "cr3"))
        self.metaFileFormatComboBox.setItemText(7, _translate("MainWindow", "dng"))
        self.metaFileFormatComboBox.setItemText(8, _translate("MainWindow", "dr4"))
        self.metaFileFormatComboBox.setItemText(9, _translate("MainWindow", "f4a"))
        self.metaFileFormatComboBox.setItemText(10, _translate("MainWindow", "gif"))
        self.metaFileFormatComboBox.setItemText(11, _translate("MainWindow", "heic"))
        self.metaFileFormatComboBox.setItemText(12, _translate("MainWindow", "heif"))
        self.metaFileFormatComboBox.setItemText(13, _translate("MainWindow", "jpeg"))
        self.metaFileFormatComboBox.setItemText(14, _translate("MainWindow", "jpg"))
        self.metaFileFormatComboBox.setItemText(15, _translate("MainWindow", "m4a"))
        self.metaFileFormatComboBox.setItemText(16, _translate("MainWindow", "mos"))
        self.metaFileFormatComboBox.setItemText(17, _translate("MainWindow", "mov"))
        self.metaFileFormatComboBox.setItemText(18, _translate("MainWindow", "mp4"))
        self.metaFileFormatComboBox.setItemText(19, _translate("MainWindow", "nef"))
        self.metaFileFormatComboBox.setItemText(20, _translate("MainWindow", "orf"))
        self.metaFileFormatComboBox.setItemText(21, _translate("MainWindow", "ori"))
        self.metaFileFormatComboBox.setItemText(22, _translate("MainWindow", "pdf"))
        self.metaFileFormatComboBox.setItemText(23, _translate("MainWindow", "png"))
        self.metaFileFormatComboBox.setItemText(24, _translate("MainWindow", "raf"))
        self.metaFileFormatComboBox.setItemText(25, _translate("MainWindow", "raw"))
        self.metaFileFormatComboBox.setItemText(26, _translate("MainWindow", "rw2"))
        self.metaFileFormatComboBox.setItemText(27, _translate("MainWindow", "rwl"))
        self.metaFileFormatComboBox.setItemText(28, _translate("MainWindow", "sr2"))
        self.metaFileFormatComboBox.setItemText(29, _translate("MainWindow", "srw"))
        self.metaFileFormatComboBox.setItemText(30, _translate("MainWindow", "tiff"))
        self.metaFileFormatComboBox.setItemText(31, _translate("MainWindow", "x3f"))
        self.creatorLabel.setText(_translate("MainWindow", "Creator:"))
        self.titleLabel.setText(_translate("MainWindow", "Title/Headline:"))
        self.descriptionLabel.setText(_translate("MainWindow", "Description:"))
        self.writerLabel.setText(_translate("MainWindow", "Writer:"))
        self.keywordLabel.setText(_translate("MainWindow", "Keywords:"))
        self.cityLabel.setText(_translate("MainWindow", "City:"))
        self.stateLabel.setText(_translate("MainWindow", "State:"))
        self.countryLabel.setText(_translate("MainWindow", "Country:"))
        self.copyrightLabel.setText(_translate("MainWindow", "Copyright:"))
        self.loadButton.setText(_translate("MainWindow", "Load"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.writeButton.setText(_translate("MainWindow", "Write"))
        self.aiInputBoxEdit.setPlaceholderText(_translate("MainWindow", "**Provide general description about files to generate caption. Provide as much details as possible.**"))
        self.aiResetButton.setText(_translate("MainWindow", "Reset"))
        self.aiSubmitButton.setText(_translate("MainWindow", "Submit"))
